# Script for parsing the standard error files generated by 
# Java and Python programs
import requests 
import os

def parse_java_logs():
	
	# Open java log file and parse till the exception is detected
	fjava = open("java_src/Testng/test.log","r")
	for line in fjava:
		if "Exception" in line:
			print line
			exception_query_string = line.split(":")[0].strip()
			print exception_query_string
			stackExItems = queryStackExchange(exception_query_string)
			createGitHubIssue(exception_query_string, stackExItems)
				
	fjava.close()

def queryStackExchange(query):
	stackExItems = []
        url = "https://api.stackexchange.com/2.2/search/advanced?order=desc&sort=activity&q="+query.strip()+"&site=stackoverflow"
        with requests.Session() as session:
                json_response = session.get(url).json()
	stackExItems.append(json_response['items'][0]['link'])
	stackExItems.append(json_response['items'][1]['link'])
	stackExItems.append(json_response['items'][2]['link'])
	stackExItems.append(json_response['items'][3]['link'])
	return stackExItems	

def createGitHubIssue(exception_query_string, stackExItems):
	print "\n\n\n\t\t\t str = " + exception_query_string
	curl_command = 'curl --user "ashwintumma23:APGA2dPD" -i -d \'{"title": "BUILD_EXCEPTION: '+exception_query_string+'","body": "The Jenkins build failed. We have the following possible solutions on Stack Exchange which match the Exception.\\n'+str(stackExItems[0])+'\\n'+str(stackExItems[1])+'","labels": ["design"]}\' https://api.github.com/repos/ashwintumma23/LinkedInHackDay/issues'

	print curl_command
	os.system(curl_command)
	print "Done Logging issue on Github Repository"

def main():
	parse_java_logs()
#	parse_python_logs()
	

main()
